# -*- coding: utf-8 -*-
"""Project_Python_Leila.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16LU1PN3KVuWblFPgrZyp-75kRgLie6uD
"""

import pandas as pd
import numpy

# Fungsi untuk input produk


def belanja():
  shopping_list=[]
  

  flag = ""
  while(flag != "T"):
 #   index_shop = input("Nomor input belanja: ")
 #   index.append(index_shop)

    data = {}
    data["produk"] = input("Nama produk: ")
    data["jumlah"] = float(input("Jumlah produk: "))
    data["harga"] = float(input("Harga produk: "))
    shopping_list.append(data)
    
    flag = input("Apakah Anda ingin meneruskan belanja Y/T: ")
  return shopping_list

shopping_list = belanja() # untuk memanggil fungsi input produk

# update shopping list dengan user input

indeks = int(input("Masukkan baris yang ingin Anda ubah: "))
produk = input("Masukkan nama produk yang ingin Anda ubah atau perbaiki: ")
jumlah = float(input("Masukkan jumlah produk yang ingin Anda ubah atau perbaiki: "))
harga = float(input("Masukkan harga produk yang ingin Anda ubah atau perbaiki: "))

shopping_list[indeks-1] = {'produk': produk, 'jumlah': jumlah, 'harga': harga}

# menghilangkan bagian list dengan user input

indeks = int(input("Masukkan urutan baris belanja yang Anda ingin hapus: "))
shopping_list.pop(indeks-1)
shopping_list

# fungsi memanggil daftar belanja dengan tabel
def cek_belanja():
  cek = input("Apakah Anda ingin mengecek daftar belanja (Y/T): ")
  if cek == "Y" or cek == "y":
    daftar = pd.DataFrame(shopping_list)
    daftar.index = pd.RangeIndex(start=1, stop=(len(shopping_list)+1), step=1)

    return daftar
  else:
    pass
daftar = cek_belanja()

cek_belanja() # kode untuk memeriksa daftar belanja dalam tabel

daftar = cek_belanja() # kode untuk mengeluarkan dataframe dari fungsi (maaf I don't know other way to get this done)

# menghitung total belanja
subtotal = (daftar['jumlah'] * daftar['harga']).sum()
print(subtotal)

# fungsi menghitung total belanja dengan diskon yang harus dibayarkan 

def total_belanja():
  print(f'Total belanja Anda hari ini Rp: {subtotal}')

  if subtotal >= 500000:
    print(f'Yang harus Anda bayar: Rp {subtotal * 0.9}')

  elif subtotal >= 300000:
    print(f'Yang harus Anda bayar: Rp {subtotal * 0.92}')

  elif subtotal >= 200000:
    print(f'Yang harus Anda bayar: Rp {subtotal * 0.95}')

  else:
    print(f'Yang harus Anda bayar: Rp {subtotal}')

total_belanja() # code memanggil total belanja